INSERT INTO department (name)
VALUES
    ('Finance'),
    ('Sales'),
    ('Marketing'),
    ('Software Engineering');

INSERT INTO role (title, salary, department_id)
VALUES
    ('(CFO)Chief Financial Officer', 200000, 1),
    ('Finance Director', 130000, 1),
    ('Finance Manager', 100000, 1),
    ('Financial Analyst', 80000, 1),
    ('Risk Analyst', 80000, 1),
    ('Finance Assistant', 45000, 1),
    ('Junior Financial Analyst', 55000, 1),
    ('Payroll Clerk', 45000, 1),
    ('Finance Intern', 35000, 1),
    ('National Sales Manager', 100000, 2),
    ('Regional Sales Manager', 80000, 2),
    ('Branch Manager', 70000, 2),
    ('Team Leader', 50000, 2),
    ('Sales Person', 40000, 2),
    ('Marketing Director', 120000, 3),
    ('Regional Marketing Manager', 900000, 3),
    ('Branch Marketing Executive', 70000, 3),
    ('Marketing Team Leader', 60000, 3),
    ('Marketing Associate', 45000, 3),
    ('Marketing Intern', 35000, 3),
    ('Chief Engineer', 200000, 4),
    ('Director of Engineering', 160000, 4),
    ('Engineering Manager', 130000, 4),
    ('Software Engineer', 100000, 4),
    ('Network Engineer', 100000, 4),
    ('Data Engineer', 100000, 4),
    ('Junior Engineer', 80000, 4),
    ('Engineering Assistant', 60000, 4),
    ('Entry Level Engineer', 50000, 4),
    ('Engineering Intern', 35000, 4);
    

INSERT INTO employee (first_name, last_name, role_id)
VALUES
    ('James', 'Fraser', 1),
    ('Jack', 'London', 2),
    ('Robert', 'Bruce', 3),
    ('Peter', 'Greenaway', 4),
    ('Derek', 'Jarman', 5),
    ('Paolo', 'Pasolini', 6),
    ('Heathcote', 'Williams', 7),
    ('Sandy', 'Powell', 8),
    ('Emil', 'Zola', 9),
    ('Sissy', 'Coalpits', 10),
    ('Antoinette', 'Capet', 11),
    ('Samuel', 'Delany', 12),
    ('Tony', 'Duvert', 13),
    ('Dennis', 'Cooper', 14),
    ('Monica', 'Bellucci', 15),
    ('Samuel', 'Johnson', 16),
    ('John', 'Dryden', 17),
    ('Alexander', 'Pope', 18),
    ('Lionel', 'Johnson', 19),
    ('Aubrey', 'Beardsley', 20),
    ('Tulse', 'Luper', 21),
    ('William', 'Morris', 22),
    ('George', 'Shaw', 23),
    ('Arnold', 'Bennett', 24),
    ('Algernon', 'Blackwood', 25),
    ('Rhoda', 'Broughton', 26),
    ('Hart', 'Crane', 27),
    ('Vitorio', 'DeSica', 28),
    ('Wilkie', 'Collins', 29),
    ('Elizabeth', 'Gaskell', 30),
    ('George', 'Sand', 4),
    ('Vernon', 'Lee', 2),
    ('Arthur', 'Machen', 3),
    ('Frederick', 'Marryat', 4),
    ('Harriet', 'Martineau', 5),
    ('George', 'Meredith', 6),
    ('Margaret', 'Oliphant', 7),
    ('Anthony', 'Trollope', 8),
    ('Charlotte', 'Yonge', 9),
    ('Horace', 'Walpole', 14),
    ('Matthew', 'Lewis', 11),
    ('William', 'Bedford', 12),
    ('Anne', 'Radcliffe', 13),
    ('Charles', 'Brown', 14),
    ('Eliza', 'Parsons', 17),
    ('Susan', 'Hill', 16),
    ('Sydney', 'Owenson', 17),
    ('Hubert', 'Crackanthorpe', 18),
    ('William', 'Carleton', 19),
    ('Gerald', 'Griffin', 20);